name: Emojis
main: xBeastMode\Emojis\Loader
version: 1.0.0
api: [4.0.0]
load: STARTUP
author: xBeastMode
description: Adds emojis to pocketmine

permissions:
  emojis.command.spawnemojimodel:
    default: op
  emojis.emoji.all:
    default: op